/**:
    ros__parameters:
        image_transport: raw
        family: 36h11
        size: 0.108
        max_hamming: 0
        detector:
            threads: 1
            decimate: 2.0
            blur: 0.0
            refine: True
            sharpening: 0.25
            debug: False
        tag:
            ids: [0, 1]
            frames: [global_workbench1, global_workbench2]
            sizes: [0.108, 0.108]
